Making the ` torchlive-cli init` command independent of locally installed Python version
facebookresearch/playtorch pull request #9
Opened 2021-12-07 03:33 UTC by aaronespasa

## Summary

TorchVision v0.11.1 needs the version 21.3.1 from PIP. Previously to this PR, the version of PIP depended on the version of Python that was installed locally:

<img width="454" alt="Screenshot 2021-12-07 at 04 01 21" src="https://user-images.githubusercontent.com/39239895/144958395-00c44d03-e300-4e27-a4fe-965c5352ea8e.png">

See that it uses Python3, which was installed by the user. If the Python version installed locally cannot upgrade PIP to the version 21.3.1, then dependencies like TorchVision won't be installed and the command `npx torchlive-cli init MyProject` will result in an error (in the following case, Python3 has the version 3.7.12):

![064129A3-E6CD-4C2A-AC6C-3D08D2C78311_1_105_c](https://user-images.githubusercontent.com/39239895/144958605-470c7789-e2c3-4572-aa88-ea882f154ce5.jpeg)

I am pretty sure this will make the installation process much easier as the user will avoid having problems related to the Python version and will not have to worry about doing any extra step (installing an specific version of Python, creating an alias for Python3 to point to the recently installed Python, ...).

The use of the flag `--no-cache-dir` is due to ARM. I had some .whl files downloaded locally that were not available for ARM. However, at the time of installing any dependency, PIP used that wheel and I run into some errors. Maybe there will be people using Apple Silicon in my position, so I find it useful to keep it in order to make the Python installation completely independent of the existing local files.

This solution also implements a function called makeModules used just to modulate the code. This function will be shared both by MacOS and Linux. However, we use a different package manager to install Python, so they cannot be joined.

The linux implementation was not checked since PyTorchLive is initially only focused on MacOS.

In conclusion, with this approach it no longer matters which version of Python is installed locally.

## Changelog

[TEMPLATE] [TEMPLATE CREATION] - Making the `torchlive-cli init` command independent of locally installed Python version

## Test Plan

First of all, if you're using an ARM CPU, you have to replace the `make_models.js` file with the one in the following pull request: [RuntimeError related to quantization solved for ARM architecture](https://github.com/pytorch/live/pull/8). If you're using a x86 CPU it's not necessary that you perform this step.

In both cases, we're going to use the same command (feel free to change the name of the project and replace the path `/Users/aaron/Documents/github/` by your absolute path to the current working directory where you are using the command):
```bash
$ npx react-native init LiveM1Test --template file://Users/aaron/Documents/github/live/react-native-template-pytorch-live/
```

---
### Before

In this case, `python3 -V` outputs the version 3.7.12. This is the result of running the command specified before:

![064129A3-E6CD-4C2A-AC6C-3D08D2C78311_1_105_c](https://user-images.githubusercontent.com/39239895/144960302-b20f90fc-3e8c-4c66-a891-70bc1585d122.jpeg)

---
### After

In this case, `python3 -V` still outputs the version 3.7.12. However, the `script.js` file uses its own version on the virtual environment. This is the result of running the command specified before:

![C0ECFF91-E416-46E6-8306-BE474457A8AF](https://user-images.githubusercontent.com/39239895/144961103-be5329fa-7037-4f63-be24-43346c8c1a7b.jpeg)

2021-12-13 04:24 UTC, raedle requested changes
Thanks @aaronespasa for submitting this PR. There are some really good changes, but also some changes that will break the `init` on macOS and break the NLP Q&A demo, which uses the Distilbert model.

If you are up for it, happy to review another version of the PR!

2021-12-13 04:24 UTC, raedle commented on react-native-template-pytorch-live/script.js
> +    execSync('/usr/local/opt/python@3.9/bin/python3 -m venv ./venv');
The absolute path can vary depending on how Homebrew is set up.  On my machine, for example, Homebrew installs packages in my user's home directory:

```
$HOME/homebrew/opt/python@3.9
```

2021-12-13 04:24 UTC, raedle commented on react-native-template-pytorch-live/script.js
> +    execSync('pip install virtualenv');
Why install the `virtualenv` package and not rely on the `python3 -m venv`?

Let's install any development dependency as part of the `setup-dev` command, so the `init` will only initialize a project -- expected that all dependencies have been installed beforehand.

Eventually raise an error if the `virtualenv` dependency doesn't exist.

2021-12-13 04:24 UTC, raedle commented on react-native-template-pytorch-live/script.js
> +    execSync('sudo apt-get install python3.9')
Same as above. Let's install any development dependency as part of the `setup-dev` command

2021-12-13 04:24 UTC, raedle commented on react-native-template-pytorch-live/template/models/requirements.txt
> +transformers==4.11.3
@aaronespasa the Distilbert NLP Q&A example will break if the `transformers` dependency is upgraded to `4.11.3` and needs additional debugging (see screenshot)

![Simulator Screen Shot - iPhone 12 - 2021-12-12 at 20 19 41](https://user-images.githubusercontent.com/489051/145751884-1fa2793e-f949-414a-9318-600636a031a9.png)

2021-12-14 07:01 UTC, aaronespasa commented
@raedle Thank you so much for the detailed feedback, it has been very helpful to understand what are the problems and how to solve them!

I'll publish a pull request solving these bugs as soon as I can.

2022-09-14 21:09 UTC, raedle commented
Thanks @aaronespasa for the PR! The `torchlive-cli` was deprecated and removed from the PlayTorch repo (i.e., it is no longer maintained). It is recommended to follow the [React Native Environment Setup](https://reactnative.dev/docs/next/environment-setup) instructions on their website to get started with React Native development and PlayTorch

2022-09-14 21:09 UTC, closed without merging